### ISSUE TITLE
[ADR Controller] GGG temperature does not seem to work

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#10]
Nothing seems to happen when the GGG check-box is clicked. If this should be working these days, that this is likely caused by renaming of the files and servers. Specifically, I renamed server `ACBridgeWithMultiplexer` to `AC Bridge with Multiplexer` for consistency reasons. I also renamed most freshly copied (from the original repo) servers but file names should not matter at all. I modified all registry settings that I could find and one comment in one of the Python files accordingly, but mightn't have missed something.

**Comment by roboguy222** [comment]
We should double check that regulation works when the temperature is only being updated once every 10s.
