### ISSUE TITLE
Change all logging data types to float16

### ISSUE THREAD

**Issue by amopremcak** [McDermott-Group/servers#102]
I think we should change all logging data, e.g. Temperatures, Pressures, and Flow Rates, into float16 @roboguy222 & @nmGit . It will save disk space, a precious and non-renewable resource, and improve transfer speeds for datasets that span multiple weeks. We should also cut down the sampling rates of these variables as they do not change very rapidly. I don't know how to mark this as an enhancement, but if its not too much trouble it think its worth while.

**Comment by roboguy222** [comment]
Ok, the ADR controller is now in 16 bit.

**Comment by nmGit** [comment]
Done with MView. Use the data_type keyword when creating a device to specify float16. Still defaults to float32 of the keyword is not used.
