### ISSUE TITLE
Do not display an old reading value when the actual reading is NaN

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#106]
For example, when the ```mix_temperature``` setting returns ```Value(nan, 'mK')```, the Leiden DR GUI still shows 13.43 mK. This is not good since such behavior can potentially lead to a wrong conclusion/action. It is reasonable to assume that the displayed numbers are "real-time" values, not some "random" values from the past.

**Comment by nmGit** [comment]
hmm, I will take a look at this.
