### ISSUE TITLE
Time buttons (at least "10 min" and "2 hours") do not work properly

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#109]

**Comment by nmGit** [comment]
Interesting... would you mind taking a few screenshots if you can get it to happen again? I am having trouble replicating the issue.

**Comment by patzinak** [comment]
I don't see it happening now. If I don't see it happening again for some time and if there are no other major problems I'll close this issue. I realized that before reporting this issue I saw another problem: somehow the temperatures that are read by your magic box were not being updated. Restarting the GUI didn't help but restarting the computer solved the issue. So, it could be that the actual issue was with (absence of) the readings from the box.

**Comment by nmGit** [comment]
when you restarted the gui, did you also restart the labrad servers? Specifically the serial server as well as the 'magic box' server?

**Comment by patzinak** [comment]
Yes, I restarted everything.

**Comment by patzinak** [comment]
Haven't seen bug in a while. I'll reopen the issue if I notice this behavior again.
