### ISSUE TITLE
[ADR Controller] AsyncServerWrapper errors

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#11]
Upon the GUI startup the log window shows a cryptic message: "Could not connect to device: 'AsyncServerWrapper' object has no attribute 'select_device'". The ADR3 servers also tells that this 'AsyncServerWrapper' can has no attribute 'add_channel'. If this is related to the fact the serial devices are not properly connected than please close the issue. If this behavior is unavoidable but is algorithmically acceptable, then please do not highlight this specific message in red (or remove it at all) to avoid any confusions.

**Comment by patzinak** [comment]
Btw, you should now be able to start the GUI and all servers by running `startup.py` on mcd-adr3. We can create a couple-liner script and name it `adr3.py` if you like. I remember you had an opinion here — feel free to create as many scripts as you want that point to the startup.py.

**Comment by roboguy222** [comment]
This was on purpose because the old labrad made error handling somewhat difficult.  In the new labrad this is easier, so I have done away with these messages :).

**Comment by patzinak** [comment]
Great, thank you! Just unimportant advice on [closing GitHub issues](https://help.github.com/articles/closing-issues-via-commit-messages/).
