### ISSUE TITLE
Important cosmetic improvements

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#111]
1. Dilution Unit Temperatures should be in the following order:
Still Temperature
Exchange Temperature
Mix Temperature

This used to be the case but somehow the order is changed now.

2. There should be four digits after the dot for the pressure readings in the Vacuum frame to allow the display of the typical lower values. Again, this is used to be the case.

3. It would be great if the compressor temperature readings would be in deg. C if this isn't hard. In any case, the second digit after the dot is useless. So, just one decimal place is more than enough.

**Comment by patzinak** [comment]
4. Make the plot tools symmetric with respect to the option available for the X and Y axes.

**Comment by nmGit** [comment]
All done.
