### ISSUE TITLE
Notifier email message title does not match with the message body.

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#113]
Title of the email I received:
```Compressor:Oil Temperature```

Message body of the same email:
```['04/12/17 at 13:05:06 | Water Flow->External Water Flow Rate: 0.93gal/min | Range: 1.2gal/min - 3.0gal/min.', '']```

**Comment by nmGit** [comment]
I will have to go through the code more, but for now the issue is fixed.
