### ISSUE TITLE
[mView] Change config filenames to match parent GUI scriptname

### ISSUE THREAD

**Issue by iamed18** [McDermott-Group/servers#116]
At present, only one mView GUI may be present in a given directory due to mView.config being a static filename provided from mView. An easy way to get around this would be to have each GUI script that invokes mView own a unique config file. 

Example: the Leiden monitoring software is launched from an mView script titled `LeidenGui.py`. This could generate the relevant files needed and could control uniqueness via prepending them with the basename of the script (e.g. `LeidenGui.mView.config` and `LeidenGui.mView.notifierConfig` or something like that).

This will make it such that multiple mView GUIs can exist in a given directory without creating config file conflicts within said directory.

**Comment by nmGit** [comment]
Done
