### ISSUE TITLE
[dataChest] overwrite = True parameter not required to overwrite Dataset parameters

### ISSUE THREAD

**Issue by czimonick** [McDermott-Group/servers#119]
With the overwrite parameter unset or set to False, one can still overwrite extant parameters with dataChest.addParameter() without any sort of exception being thrown, and the old parameter is actually overwritten.

**Comment by amopremcak** [comment]
I'll take a look at this soon.

**Comment by amopremcak** [comment]
Fixed. Backwards compatibility ....
