### ISSUE TITLE
[SIM 900 Server] KeyError: 'SIM900'

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#12]
From the error log:

```
<...>
File "sim_900_server.py", line 80, in refreshDevices
  p = self.client[self.name].packet()
File "C:\Python\<...\labrad\wrappers, line 624, in __getitem__
 return self.servers[key]
<...>
exceptions.KeyErorr: 'SIM900'
```

I have not modified the server in any way and have been running this version without any problems on Leiden for a long time. This error does not always pop up and does not obviously interfere with the GUI performance, i.e. the temperature is read correctly whether or not this error appears. The servers were started with the LabRAD node.

**Comment by roboguy222** [comment]
if this error occurs, the server now waits for 100ms and tries again.  I think it is being caused by a delay in the manager recognizing the server.
