### ISSUE TITLE
[ADR GUI] Not user-friendly behavior upon reaching maximum magnet current

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#16]
1. One has to manually press "Stop Magging Up" button before magging down even though the current stays above 9A (reads 9.00581 A) for a half an hour.
2. When target temperature is chosen to be 0 K, the log box shows "Starting regulation to 0.1 K from 9.00581" but the regulation box shows 0 K. This is confusing.

**Comment by patzinak** [comment]
1. Regulation is completed when the current is still quite high (a good fraction of an ampere, TmK > 120 mK). Do not display the log message until the current reading is less than let's say 0.01 A or remove phrase "Mag up and try again."

**Comment by roboguy222** [comment]
This has been changed from stopping regulation when the voltage is close to 0 to stopping when the current is close to 0.
