### ISSUE TITLE
[ACBridgeWithMultiPlexer] things get weird if accessed from different contexts

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#18]
Basically, multiple loops are going at the same time trying to take temperature.  If one context accesses some multiplexer and adds channels, and another context does the same, those channels should be added into the same array, not separate loops for each context.  This is common if we just restart the adrserver, so it is quite important.  A global dict needs to be created holding the channels for each device, instead of storing them in c.

**Comment by patzinak** [comment]
Is this is a case when the device locks should be used? I think GPIB server may have them implemented but I've never used them.

**Comment by roboguy222** [comment]
I don't think we want to use device locks here, no.  Both contexts should
still be able to access the server I think.
