### ISSUE TITLE
[ADR Server] Use data chest/vault to store temps, etc

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#24]
(once the data chest is finished and usable)

**Comment by amopremcak** [comment]
datetime datatype will be added by today, but possibly too late at night to be useful to you.

**Comment by roboguy222** [comment]
Challenge accepted.  Lmk when you finish.

**Comment by amopremcak** [comment]
Failed challenge. One Wilen, Zero Opremcak.

**Comment by amopremcak** [comment]
dataChest accepts utc_datetime strings now.

**Comment by roboguy222** [comment]
ADR implemented.  Need to transfer all the old files.  Also change where the log files are stored.

**Comment by roboguy222** [comment]
Logs transferred for ADR3.  Given this program has not yet been seriously used for ADR1&2, I am just deleting those logs.
