### ISSUE TITLE
[DataChest, Grapher] Make d.cd() handle string path

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#35]

**Comment by amopremcak** [comment]
As in `d.cd("nextFolder\nextNextFolder\nextNextNextFolder")` so that a folder with path pwd + "nextFolder\nextNextFolder\nextNextNextFolder" is created? @roboguy222

**Comment by roboguy222** [comment]
Same as using an array, just string for instead

"nextFolder\nextNextFolder\nextNextNextFolder" = ["nextFolder","nextNextFolder","nextNextNextFolder"]

**Comment by amopremcak** [comment]
Word

**Comment by amopremcak** [comment]
This is now implemented. Both forward and backward slashes are accepted, though using both styles in the same string is prohibited. The functionality is implemented as you suggested above. The document needs to be updated to reflect these changes but I am closing this as a document related issue already exists.
