### ISSUE TITLE
[dateStamp] creating date stamp with string including time zone information fails

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#40]
Normally we get the string to pass to the datestamp with `utc.isoformat()` or whatever, but if this has timezone info associated it, a `+00:00` or whatever the offset is is added onto the end.  `dateStamp()` errors out in this case.

**Comment by amopremcak** [comment]
This issue is related to a lack of documentation for the dateStamp class. The method ```dateStamp.dateStamp``` now excepts an optional argument named ```utcDateISO``` as opposed to just ```dateISO``` which was the original source of confusion. This method was never intended to handle strings with a timezone offset.
