### ISSUE TITLE
[ADR Client] Mag up/regulate buttons need to change when instrument statuses change

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#43]

**Comment by roboguy222** [comment]
Actually I am not sure this is needed.  It already gives an error and refuses to start of the necessary instruments are not connected.  It is easier for users to tell what is wrong if they are allowed to click mag up and then it tells them the power supply is off, as opposed to just not being able to click on the button.  @patzinak, agree?

**Comment by patzinak** [comment]
This is fine with me.
