### ISSUE TITLE
PT1000s y-axis is unlabeled

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#48]
The axis should be labeled as "Temperature (K)".

**Comment by patzinak** [comment]
The same bug appears on the Flow Meter graph. Label "Flow Rate (gal/min)" is required.

**Comment by patzinak** [comment]
The same bug is on the Vacuum plot. Either label "Pressure (bar)" or "Pressure (mbar)" is required. The later one is preferred but the first one is okay too.

**Comment by patzinak** [comment]
Also, there might be or might not be a problem with the units on the Vacuum plot. Please, double check the values on the plot.

**Comment by nmGit** [comment]
I will take a look at this, I probably forgot to tell mView what the y axis should be.

**Comment by nmGit** [comment]
Fixed, i think
