### ISSUE TITLE
Source code lines are too long! 

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#52]
Please shorten the coe lines to 72 characters, or at least to the length such that they are fully readable on GItHub. I can not fully read the comments on GitHub.

For example,  lines 225 and 226 in servers/GUI/mView/dataChestWrapper.py;
lines 212-216 in  servers/GUI/mView/MGrapher.py;

**Comment by nmGit** [comment]
Most source code lines were shortened.
