### ISSUE TITLE
Remove all code that was used for debugging

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#53]
There are lots of code chunks that are commented out and likely were used for debugging. Remove them out (preferably) or write a comment regarding the potential need for this commented code.

**Comment by patzinak** [comment]
For example, lines 70, 73, 103, 107-112, 114, 129-132, 262-269, 280-284 in servers/GUI/mView/NotifierGUI.py

**Comment by nmGit** [comment]
I can suppress output and remove a lot of the code for debugging, but I hesitate to remove it all because the code _is_ still under active development and will be for a long time. The debugging code is extremely useful for quickly fixing bugs.

**Comment by patzinak** [comment]
`print("here")` is not a useful debugging feature... But sure, keep important logical blocks (or create a new branch when you adding a totally new feature). It is okay to have commented something like this: `print("Number of servers running: %d", number_of_servers)` because this statement indirectly tells you what is important at this point of the code execution, it is a some sort of a comment. But `print('working')` is no okay.

**Comment by nmGit** [comment]
All extra debugging code removed.
