### ISSUE TITLE
[ADR GUI] MagUp button did not start mag-up after the magnet was cycled

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#68]
After closing the heat switch on ADR3 and seeing the FAA temperature rising from about 0.5 K to about 3.3 K, I attempted a new mag-up but neither the current nor back-EMF was showing any change for a minute or so. The MagUp button became disabled as expected and the corresponding message was printed in the log window but no actual change in current/voltage/back-EMF was visible. "Stopping" the mag-up and starting it again didn't help, refreshing the instruments didn't help.

After closing the LabRAD-related windows and restarting everything, the GUI started working properly.

**Comment by roboguy222** [comment]
I have never seen this before, and without being able to query the servers, this is impossible to diagnose.  Did you notice anything printed to the node window?  Were all the instruments green at the top of the GUI (except the heat switch)?

**Comment by patzinak** [comment]
Yes, all instruments were marked green and nothing weird was noticeable. It kind of felt like everything works well and there is just a little bug in an "if" statement that should allow the start of the actual process but it doesn't. Let's keep an eye on this.

**Comment by roboguy222** [comment]
Sounds like the computer in general was acting pretty weird at this time too and needed to be restarteed.  I am going to close this issue until it happens again and we have more info.
