### ISSUE TITLE
[dataChest] mkdir unexpected behavior

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#69]
Not sure this is a bug or a feature :) If you run

``` python
from dataChest import *
a = dataChest('a')
b = dataChest('b')
a.mkdir('c')
```

then the folder 'c' is created inside folder 'b', not inside folder 'a', as I was intuitively expected.

@amopremcak close the issue or relabel it as a bug.

**Comment by amopremcak** [comment]
This was a bug. It is now fixed.
