### ISSUE TITLE
Matlab files are being saved twice as large as necessary

### ISSUE THREAD

**Issue by bgchristensen** [McDermott-Group/servers#72]
If I load a saved matlab data file, and then resave it, the size is reduced by approximately 0.5.  How are we currently saving the matlab files?  There may be a more efficient way of saving?  It also just might be an issue with python itself (probably since we're using 32-bit)

Basically, I load a matlab data file of size 127 kB.  I then resave the file and it will be of size 68 kB.

**Comment by patzinak** [comment]
I've run one test and I saw a datafile getting down in size from 150 kB to 130 kB. Not as significant change.

We use `scipy.io.savemat()` to save the data. It appears that this method has a flag `do_compression` that is set to `False` by default. I'm changing this in the next commit.
