### ISSUE TITLE
Insert word-separating whitespaces in the plot legends

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#77]

**Comment by patzinak** [comment]
Quickly checked the new GUI - looks really great. I assume you will eventually replace the underscores with the whitespaces. Also, it would be great if you remove the trailing decimal zeros in the time stamps on the horizontal axis. We will never need such precision and I doubt that there is any actual physical meaning in these zeros.

**Comment by nmGit** [comment]
Done. Because datachest does not allow spaces, the workaround is to use underscores in place of spaces and then change those underscores back into spaces when displaying the legend.
close
