### ISSUE TITLE
FAA and GGG temperature are not plotted/read correctly

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#83]
The ADR3 GUI shows that the FAA tempertaure is 736 mK, the GGG temperature is 587 mK, while SIM921 displays 92 mK.

**Comment by patzinak** [comment]
The problem was solved when everything was restarted. Pressing `Refresh Devices` did not help (the device statuses were all green except for the switch). This might be related to [this issue](https://github.com/McDermott-Group/servers/issues/81).

**Comment by roboguy222** [comment]
As far as I know this problem has not reoccurred, so I am closing this issue.
