### ISSUE TITLE
[ADR Server] Not context safe

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#86]
If we call methods like `stopCompressor,` we don't use the same context for all requests from that adr device.

**Comment by patzinak** [comment]
I have not tested this, but I think if I select_device for a given instrument type that is also being used for the ADR, it will change that address for the ADR as well since now my context says it should?

**Comment by nmGit** [comment]
I ran into this with the MKS PDR2000's a while ago, is it the same problem? I fixed it with deferred locking:
```python
def rw_line(self, code):
        # Don't allow two concurrent read/write calls.
        
        self._lock = DeferredLock()

        return self._lock.run(partial(self._rw_line, code))

    @inlineCallbacks
    def _rw_line(self, code):
        '''Write data to the device.'''
        yield self.server.write_line(code, context=self.ctx)
        time.sleep(0.2)
        ans = yield self.server.read(context=self.ctx)
        returnValue(ans)
```

**Comment by roboguy222** [comment]
I think, since the adr server does not use any contexts passed down from other clients, it creates its own context, and this should not actually be a problem.  Closing issue.
