### ISSUE TITLE
Merge Tek 11801C sampling scope server to this repo

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#9]
We should merge in the server from the old repo into this one. It should be tested beforehand though, as I tried to use it today and could not communicate with the scope over GPIB -- no devices are listed.

**Comment by amopremcak** [comment]
I connected the instrument to gpib on mcdermott5125-2 and was able to interface with it just fine. I will leave this open for the next day or so but I think that it is working. It could definitely use some enhancements however...

**Comment by gribeill** [comment]
Bug fixed, leaving this open for enhancement but core functionality exists, namely the ability to pull trace data from the scope. Lets test is out as stands and if new settings/methods are desired we can make it happen. 
-AMO

**Comment by patzinak** [comment]
I renamed the server file and cleaned it up a bit. Let's try to make the coding style consistent across the repo as much as we can. It helps a lot when you are trying to debug something later.
