### ISSUE TITLE
Slow file dialogue in Qt

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#91]
The file dialogue in Qt takes around 10 seconds to open for some reason.  A good example of this is pressing the select file button in the probe station code.  I think it only happens on Windows.  This is low priority to fix, but would be good to get taken care of for the sake of future code.

**Comment by nmGit** [comment]
Try using QtGui.QFileDialog.getSaveFileName in line 132 of MDataSetConfigGui. It opens immediately, but takes a few seconds to return once closed which is much less noticable.

**Comment by nmGit** [comment]
Is this still an issue?
