### ISSUE TITLE
No need for setting `TemperaturesForGUI` in cryomech_cp2800_compressor.py

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#94]
@nmGit There is no need for this setting. The servers should know absolutely nothing about the existence of any GUI. If you really have to keep it, please rename it to `Current Temperatures` and remove the unnecessary print statement, whitespace and add a line to separate from the next method.

**Comment by patzinak** [comment]
@roboguy222 Do you use this setting anywhere in your ADR code? If not, I'll go ahead and rename it to 'Current Temperatures'.

**Comment by nmGit** [comment]
That is fine, you will need to change the setting names in LeidenGui.py:

 Compressor = Device("Compressor")
        Compressor.connection(cxn)
        Compressor.setServerName("cp2800_compressor")
        Compressor.addButton("Turn Off",
                "You are about to turn the compressor off.",
                "stop", None)
        Compressor.addButton("Turn On",
                "You are about to turn the compressor on.",
                "start", None)
        Compressor.addParameter("Input Water Temperature",
                "**temperaturesforgui**", None, 0, 'degC', 1)
        Compressor.addParameter("Output Water Temperature",
                "**temperaturesforgui**", None, 1, 'degC', 1)
        Compressor.addParameter("Helium Temperature",
                "**temperaturesforgui**", None, 2, 'degC', 1)
        Compressor.addParameter("Oil Temperature",
                "**temperaturesforgui**", None, 3, 'degC', 1)
        Compressor.selectDeviceCommand("select_device", 0)
        Compressor.setYLabel("Temperature")
        Compressor.addPlot()
        Compressor.begin()
        self.devices.append(Compressor)

**Comment by nmGit** [comment]
All that that setting does is format the readings in a way that MView is happy with.

**Comment by patzinak** [comment]
Yes, I understand this. I'm totally fine to keep the setting but it should be renamed to "Only Current Temperatures" to reflect its actual difference from the other setting. Again, the existence of GUIs should not have any influence on the design of the servers.

**Comment by roboguy222** [comment]
I do not use this feature anywhere, no.
