### ISSUE TITLE
OK button does not work in the GUI DataChest Config window

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#97]
This is probably work in the progress but want to post it here so that it is not forgotten. Also, the dialog interface seems unnecessary heavy. I can't imagine a situation when you want to log the readings in totally different places. You simply shouldn't do. The things could be simplified in the following way: everything is stored under the DATACHEST_ROOT_FOLDER, the user provide a subfolder (could be a few layers down), all the logs are stored in that subfolder. As long as the structure is consistent this should be fine. Alternatively, again, under the dataChest root there are fixed subfolders a couple layers down for all variables. User provide a name for a subfolders (or to be appended to the files) in all these folders.

I'd like to see a very simple interface where you provide a pathname  and somehow the data is properly organized is stored. The selection boxes for all variables is a great idea! We shouldn't however have 20 different buttons to select 20 different folders for the logs, this will eventually become a mess. The simpler — the better.

**Comment by nmGit** [comment]
ok, thanks for the feedback. i might teamview in and take a look at it running with multiple devices (all I have been testing it with is a very simple random number generator)

**Comment by nmGit** [comment]
also about the ok button not working, sometimes it takes several seconds after exiting the file dialog for the gui to become active again. Does it work if you give it a few seconds before trying to clock it?

**Comment by nmGit** [comment]
Ok, I teamviewed in and fixed it

**Comment by nmGit** [comment]
#close

**Comment by nmGit** [comment]
Ok so what I did was add a tab called 'basic' that just allows you to do easily edit data logging stuff and then and 'advanced' tab if the user wants it. I implemented these changes on the LeidenGui just now.

**Comment by patzinak** [comment]
Yes, this looks good to me. I haven't tested it (want to keep the current log for longer time) but this should do the job.
