### ISSUE TITLE
LeidenGUI got broken by one of the last commits

### ISSUE THREAD

**Issue by patzinak** [McDermott-Group/servers#99]
@nmGit , when you make changes please log in to the Leiden desktop computer and make sure that the program run smoothly there, try not to push the changes to the main branch unless you have some confidence they work.

**Comment by nmGit** [comment]
Ok, I will take a look

**Comment by nmGit** [comment]
It works now, sorry about that.

Close

**Comment by patzinak** [comment]
Thank you so much!

**Comment by nmGit** [comment]
I think I somehow accidentally deleted the notifier settings. Sorry Ivan, but I don't know the exact values you had. I think that you will need to re-enter them. Sorry about that

**Comment by patzinak** [comment]
Not a big deal.
